project:
  type: website

website:
  title: "Group Project"
  navbar:

      
      
    right:
      - icon: "bi bi-house-fill" 
        href: index.qmd
        text: Home
      - text: "Teams"
        menu:
          - text: "Proposal"
            href: Teams/Proposal/proposal.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

