project:
  type: website

website:
  title: "Group Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
    right:
      - icon: "bi bi-house-fill" 
        href: index.qmd
        text: Home
      - icon: "bi bi-File-earmark-person"
        href: about.qmd
        text: About


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

