project:
  type: website

website:
  title: "Group Project"
  navbar:

      
      
    right:
      - icon: "bi bi-house-fill" 
        href: index.qmd
        text: Home
      - text: "Teams"
        menu:
          - text: "Proposal"
            href: Teams/Proposal/proposal.qmd
          - text: "Meeting Minutes"
            href: Teams/Minutes/Meeting_Minutes.qmd
      - text: "Prototype"
        menu:
          - text: "Exploratory Data Analysis & Confirmatory Data Analysis"
            href: Prototype/EDA/Take-home_Ex03.qmd
          - text: "Predictive Modeling"
            href: Prototype/Predictive/Take-home_Ex3.qmd
          
            


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

